wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: huggingface
    huggingface_version: 4.16.0.dev0
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1642907517
    t:
      1:
      - 1
      - 11
      4: 3.8.10
      5: 0.12.9
      6: 4.16.0.dev0
      8:
      - 1
      - 5
